### PR TITLE
ci: Add Docker build

### PR DESCRIPTION
**Pull request by davidgubler**

### CODE REVIEW

**Review by mhutter — APPROVED** [review]

**Comment by mhutter** [comment]
This should be stored in the GHCR now; this would also simplify the CI job (login should "just work") IIRC

**Comment by davidgubler** [comment]
> This should be stored in the GHCR now; this would also simplify the CI job (login should "just work") IIRC

Well nope.

Bildschirmfoto vom 2023-04-03 13-05-18

**Comment by davidgubler** [comment]
Doesn't work without authentication either.

I think one of the problems with the GHCR is that the image must be called like the repository, thus in this case here a repo called "appcat-cli" can't publish an image called "k8ify-appcat". Thus we'd need an entirely different repo just to build the "k8ify-appcat" image and trigger builds there based on tags in this repo here (not sure if this is even possible). This is well beyond the scope of what I'm trying to achieve here hence I think I'll leave things as they are now.

**Comment by mhutter** [comment]
Fine by me, I'd still skip pushing to Docker Hub for now. That way we have one "authoritative" source of our image, instead of two.

**Comment by davidgubler** [comment]
I'd like to keep supporting DockerHub for several reasons:
* It's the first place for people to look for something
* It's also used for k8ify
* I don't see us ever stop using DockerHub
* It's the best integrated into GitHub because for DockerHub we have organization secrets and it's the only one that actually just works

**Review by martini-source — APPROVED** [review]

**Comment by davidgubler** [comment]
I'm still looking into GHCR support, I will report back once I have more specific findings.

**Comment by davidgubler** [comment]
It turns out that the image naming restriction _was_ a problem with the old GitHub registry before ghcr, but the problem does no longer exist. Therefore we can use ghcr just fine and I'll remove support for DockerHub and quay as requested. Also somebody apparently changed the default for images from private to public in the VSHN org, therefore another problem with ghcr seems to be a thing of the past.

I'll also create a follow-up for switching k8ify over to ghcr for consistency.

**Comment by davidgubler** [comment]
Removed k8ify-appcat from Quay and Dockerhub, created follow-up ticket for migrating k8ify. Therefore I think this is done.

**Pull request merged**
